// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io"
	"io/fs"

	mock "github.com/stretchr/testify/mock"
)

// NewMockReader creates a new instance of MockReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReader {
	mock := &MockReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReader is an autogenerated mock type for the Reader type
type MockReader struct {
	mock.Mock
}

type MockReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReader) EXPECT() *MockReader_Expecter {
	return &MockReader_Expecter{mock: &_m.Mock}
}

// InfoFile provides a mock function for the type MockReader
func (_mock *MockReader) InfoFile(index int) (fs.FileInfo, error) {
	ret := _mock.Called(index)

	if len(ret) == 0 {
		panic("no return value specified for InfoFile")
	}

	var r0 fs.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (fs.FileInfo, error)); ok {
		return returnFunc(index)
	}
	if returnFunc, ok := ret.Get(0).(func(int) fs.FileInfo); ok {
		r0 = returnFunc(index)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(index)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReader_InfoFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InfoFile'
type MockReader_InfoFile_Call struct {
	*mock.Call
}

// InfoFile is a helper method to define mock.On call
//   - index int
func (_e *MockReader_Expecter) InfoFile(index interface{}) *MockReader_InfoFile_Call {
	return &MockReader_InfoFile_Call{Call: _e.mock.On("InfoFile", index)}
}

func (_c *MockReader_InfoFile_Call) Run(run func(index int)) *MockReader_InfoFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReader_InfoFile_Call) Return(fileInfo fs.FileInfo, err error) *MockReader_InfoFile_Call {
	_c.Call.Return(fileInfo, err)
	return _c
}

func (_c *MockReader_InfoFile_Call) RunAndReturn(run func(index int) (fs.FileInfo, error)) *MockReader_InfoFile_Call {
	_c.Call.Return(run)
	return _c
}

// NumFile provides a mock function for the type MockReader
func (_mock *MockReader) NumFile() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NumFile")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockReader_NumFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NumFile'
type MockReader_NumFile_Call struct {
	*mock.Call
}

// NumFile is a helper method to define mock.On call
func (_e *MockReader_Expecter) NumFile() *MockReader_NumFile_Call {
	return &MockReader_NumFile_Call{Call: _e.mock.On("NumFile")}
}

func (_c *MockReader_NumFile_Call) Run(run func()) *MockReader_NumFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReader_NumFile_Call) Return(n int) *MockReader_NumFile_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockReader_NumFile_Call) RunAndReturn(run func() int) *MockReader_NumFile_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type MockReader
func (_mock *MockReader) Read(index int) ([]byte, error) {
	ret := _mock.Called(index)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) ([]byte, error)); ok {
		return returnFunc(index)
	}
	if returnFunc, ok := ret.Get(0).(func(int) []byte); ok {
		r0 = returnFunc(index)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(index)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReader_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockReader_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - index int
func (_e *MockReader_Expecter) Read(index interface{}) *MockReader_Read_Call {
	return &MockReader_Read_Call{Call: _e.mock.On("Read", index)}
}

func (_c *MockReader_Read_Call) Run(run func(index int)) *MockReader_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReader_Read_Call) Return(bytes []byte, err error) *MockReader_Read_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockReader_Read_Call) RunAndReturn(run func(index int) ([]byte, error)) *MockReader_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type MockReader
func (_mock *MockReader) Write(w io.Writer, index int) error {
	ret := _mock.Called(w, index)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(io.Writer, int) error); ok {
		r0 = returnFunc(w, index)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReader_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockReader_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - w io.Writer
//   - index int
func (_e *MockReader_Expecter) Write(w interface{}, index interface{}) *MockReader_Write_Call {
	return &MockReader_Write_Call{Call: _e.mock.On("Write", w, index)}
}

func (_c *MockReader_Write_Call) Run(run func(w io.Writer, index int)) *MockReader_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Writer
		if args[0] != nil {
			arg0 = args[0].(io.Writer)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReader_Write_Call) Return(err error) *MockReader_Write_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReader_Write_Call) RunAndReturn(run func(w io.Writer, index int) error) *MockReader_Write_Call {
	_c.Call.Return(run)
	return _c
}
